
# 数据库连接信息配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    # thymeleaf 配置视图解析
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis-plus 打印日志和 sql
  global-config:
    db-config:
      logic-delete-field: delStatus # 全局逻辑删除的实体属性名(since 3.3.0,配置后可以忽略不配置实体属性 @TableLogic 注解)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/*Mapper.xml # 配置 xml 扫描
server:
  port: 8081
